sudo: required

services:
  - docker

script:
- make cog-book
- mkdir docs/
- cp -R build/cog-book/html/* docs/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
