== Managing Bundles
:description: How to deploy and manage bundles

This document details the commands used to manage bundles.

All command bundles (with the exception of the embedded `operable` bundle) run under one or more https://github.com/operable/go-relay[Relay] processes, which can be on the same machine as the Cog bot or on different machines.

To learn more about <<Commands and Bundles, bundles>> or <<Installing and Managing Relays, relays>> check out the corresponding docs.

=== Prerequisites

For simplicity we will be using https://github.com/operable/cogctl[cogctl] to demonstrate bundle management. Bundle management mostly involves use of the 'bundles' subcommand. However, you aren't explicitly required to use `cogctl` to manage bundles, you can just make calls to the api directly if you like, but it does make things a bit easier.

So given that, I'm going to assume you have a working installation of both Cog, Relay and `cogctl`.

=== Installing bundles

Bundles are installed by uploading bundle configs to Cog. Cog then registers the bundle. Registration includes the creation of the permissions declared by the bundle, as well as any default rules specified in the bundle's metadata.

NOTE: After installation your command will be available but it may not be executable by anyone yet. Before anyone can execute the new command, make sure their permissions are set properly. Check out <<Permissions and Rules>> to learn more.

Bundles are installed via the `bundle install` sub-command in cogctl.

[source, bash]
----
$ cogctl bundle install --help
Usage: cogctl bundle install [<file>] [-t [<templates>]] [-e [<enabled>]]
                             [-v [<verbose>]]
                             [--relay-groups [<relay-groups>]]
                             [-? [<help>]] [-h [<host>]] [-p [<port>]]
                             [-s [<secure>]] [-U [<rest_user>]]
                             [-P [<rest_password>]]
                             [--profile [<profile>]]

  <file>               Path to your bundle config file (required)
  -t, --templates      Path to your template directory [default: templates]
  -e, --enable         Enable bundle after installing [default: false]
  -v, --verbose        Verbose output [default: false]
  --relay-groups       List of relay group names separated by commas to
                       assign the bundle [default: undefined]
  -?, --help           Displays this brief help [default: false]
  -h, --host           Host name or network address of the target Cog
                       instance [default: undefined]
  -p, --port           REST API port of the target Cog instances [default:
                       undefined]
  -s, --secure         Use HTTPS to connect to Cog [default: false]
  -U, --rest-user      REST API user [default: undefined]
  -P, --rest-password  REST API password [default: undefined]
  --profile            $HOME/.cogctl profile to use [default: undefined]
----

=== The config file

The only required argument for `cogctl bundle install` is the path to the bundle config file.

All bundles have a config file. The file is formatted in yaml and contains information for installing and executing commands in your bundle. To learn more about config files read up on <<Bundle Configs>>. We won't talk in detail about bundle configs in this doc, but minimally the file must contain:

* *name* - The name of your bundle
* *version* - The version of your bundle in semver format.

NOTE: Version must be a string. If you drop the patch number from the version, yaml will interpret it as a number and the config will fail validation. So if you want to just use major and minor numbers, wrap the version in quotes. ex: "0.1"

* *cog_bundle_version* - The version of the config file format (currently we only support version 2)
* *commands* - A hash of commands to be included with the bundle

A minimal bundle config might look something like this:

[source, YAML]
----
---
name: my_bundle
version: "0.1"
cog_bundle_version: 3
commands:
  date:
    executable: /bin/date
    rules:
    - "allow"
----

The command to install the bundle would be `cogctl bundle install /path/to/my_bundle.yaml`.

NOTE: A bundle is disabled when it is first installed. You must enable it before use.

=== Templates

The templates flag points to a directory containing any templates for your bundle.

NOTE: You don't need to explicitly pass the templates flag. By default cogctl looks in the current working directory for a directory named templates. And if you don't have any templates for your bundle, that's fine too. They aren't necessary for commands to work, they do make the output look nicer though :)

Templates are used by Cog to format command output. They are singular to a specific command/adapter combo. So for example; if we wanted to support both HipChat and Slack for our date command, we would need to supply two templates.

When added to the config file the templates section might look something like this:

[source, YAML]
----
---
...
templates:
  date:
    body: |
      ~each var=$results~
      `~$item.date~`
      ~end~
...
----

This works great for simple templates, but can get confusing when things start to get more complicated. To remedy that cogctl provides some helpers.

By default `cogctl` looks in the current working directory for a directory named `templates`. If your templates are located elsewhere you can optionally supply a path to your templates directory with the `--templates` option. The directory should contain one directory per adapter and each adapter directory should contain a mustache file for each command. So for our date command we would have something like this:

[source, Bash]
----
$ tree templates
templates
└── date.greenbar
----

Given a structure like this `cogctl` will automatically append all of the templates in the directory to your bundle config before uploading.

=== Enabling and Disabling Bundle Versions

When a new version of a bundle is installed it is disabled by default. Only one version can be enabled at a time and a version must be explicitly enabled before Cog will route anything to it.

Enabling and disabling bundle versions is easy. Let’s say you already have version 1.0.0 of “my-bundle” installed:

[source, Bash]
----
$ cogctl bundle versions my-bundle
VERSION STATUS
1.0.0   Enabled
----

You can install version 2.0.0 straightforwardly:

[source, Bash]
----
$ cogctl bundle install /path/to/my-bundle/v2/config.yaml
$ cogctl bundle versions my-bundle
VERSION STATUS
1.0.0   Enabled
2.0.0   Disabled
----

As always, a newly-installed bundle is disabled by default. At this point, invoking any commands from the “my-bundle” bundle will still execute from version 1.0.0.

Switching to the new version is as simple as:

[source, Bash]
----
$ cogctl bundle enable my-bundle 2.0.0
$ cogctl bundle versions my-bundle
VERSION STATUS
1.0.0   Disabled
2.0.0   Enabled
----

Now that version 2.0.0 is enabled, the update will percolate to any Relays that “my-bundle” has been assigned to. From that point, any “my-bundle” command invocations will execute from version 2.0.0, using whatever access rules have been defined in that version.

And if you decide you don’t like version 2.0.0 for any reason, you can always drop back to 1.0.0:

[source, Bash]
----
$ cogctl bundle enable my-bundle 1.0.0
$ cogctl bundle versions my-bundle
VERSION STATUS
1.0.0   Enabled
2.0.0   Disabled
----

You can also enable and disable bundles through chat commands:

[source, Cog]
----
User:
!operable:bundle disable my_bundle

Cog:
Bundle "my_bundle" version "0.1.0" has been disabled.

User:
!operable:bundle enable my_bundle 0.1.0

Cog:
Bundle "my_bundle" version "0.1.0" has been enabled.
----

NOTE: You cannot disable the embedded `operable` bundle.

==== Relay Groups

Cog manages all of your command bundles and relays. Bundles are associated to relays via relay-groups. When a bundle is installed and assigned to a relay-group, Cog pushes the command config to the appropriate relay or relays. When a command is invoked, Cog uses the relay-group to select which relay is capable of running which command.

Relay groups are managed through `cogctl` with the `relay-groups` sub-command. For more information read up on <<Installing and Managing Relays>>.

Optionally during bundle creation you can pass a comma separated list to cogctl with the `--relay-groups` option.

Bundles are assigned to relays via relay groups using `cogctl`.

[source, Bash]
----
$ cogctl relay-groups assign my_relay_group --bundles my_bundle
----

NOTE: The default refresh interval for a relay is 15 minutes (set in the relay configuration file - `relay.conf`). Be sure to wait for the specified amount time in order to see the bundle appear on the relays in the assigned relay group.

=== Uninstalling Bundles and Bundle Versions

You may uninstall a specific version of a bundle or all versions of a bundle. Uninstalling a specific version will remove rules and permissions only associated with that version. Uninstalling all bundle versions _completely_ involves removal of all authorization rules governing its commands as well as deletion of all the bundle's permissions. Any custom rules you may have written concerning the commands in the bundle will also be deleted. In this regard, bundle uninstallation is not reversible. You can re-install to get back the bundle permissions and default rules, but your custom ones will be gone forever. If you only wish to disable a bundle, see <<Enabling and Disabling Bundle Versions>> above instead.

Before a bundle can be uninstalled it must first be disabled. To uninstall a bundle just use `cogctl`.

WARNING: Since uninstalling all versions of a bundle can be quite destructive, you must pass the `--all` flag to `cogctl`. Otherwise nothing will happen.

[source, Bash]
----
$ cogctl bundle uninstall --help
Usage: cogctl bundle uninstall [<bundle_name>] [<bundle_version>]
                               [-v [<verbose>]] [-c [<clean>]]
                               [-a [<all>]] [-? [<help>]] [-h [<host>]]
                               [-p [<port>]] [-s [<secure>]]
                               [-U [<rest_user>]] [-P [<rest_password>]]
                               [--profile [<profile>]]

  <bundle_name>        Bundle name (required)
  <bundle_version>     Bundle version [default: undefined]
  -v, --verbose        Verbose output [default: false]
  -c, --clean          Uninstall all disabled bundle versions [default:
                       false]
  -a, --all            Uninstall all versions [default: false]
  -?, --help           Displays this brief help [default: false]
  -h, --host           Host name or network address of the target Cog
                       instance [default: undefined]
  -p, --port           REST API port of the target Cog instances [default:
                       undefined]
  -s, --secure         Use HTTPS to connect to Cog [default: false]
  -U, --rest-user      REST API user [default: undefined]
  -P, --rest-password  REST API password [default: undefined]
  --profile            $HOME/.cogctl profile to use [default: undefined]


$ cogctl bundle uninstall --verbose my_bundle 0.1.0
Uninstalled 'my_bundle' '0.1.0'

$ cogctl bundle uninstall my_bundle
cogctl: ERROR: "Can't uninstall 'date'. You must specify either '--all' or '--clean'."
cogctl: WARNING: "This operation is irreversible."

$ cogctl bundle uninstall date 0.1.0
cogctl: ERROR: "Cannot delete date 0.1.0, because it is currently enabled"

$ cogctl bundle uninstall date --all
cogctl: ERROR: "Cannot uninstall an enabled bundle"
cogctl: WARNING: "Version '0.1.0' of 'date' is currently enabled"

$ cogctl bundle disable date

$ cogctl bundle uninstall date --all
----
