steps:
  - command: "make html5"
    label: "Generate HTML"
    agents:
      - docker=1.12.1

  - command: "make pdf"
    label: "Generate PDF"
    agents:
      - docker=1.12.1

  - wait

  - command: "make upload"
    label: "Publish!"
    branches: "release"
    env:
      STYLESHEET_PREFIX=https://cog-book.operable.io/stylesheets
    agents:
      - docker=1.12.1
