#!/bin/sh

export TWITTER_CONSUMER_KEY=${TWITTER_CONSUMER_KEY_BOOK}
export TWITTER_CONSUMER_SECRET=${TWITTER_CONSUMER_SECRET_BOOK}
export TWITTER_ACCESS_TOKEN=${TWITTER_ACCESS_TOKEN_BOOK}
export TWITTER_ACCESS_TOKEN_SECRET=${TWITTER_ACCESS_TOKEN_SECRET_BOOK}

if [ -n "$1" ] #<1>
then
    export COG_ARGC="1"
    export COG_ARGV_0="${1}"
fi

./stats_cog_wrapper.sh <&0 #<2>
