#!/bin/bash

export TWITTER_CONSUMER_KEY=${TWITTER_CONSUMER_KEY_BOOK}
export TWITTER_CONSUMER_SECRET=${TWITTER_CONSUMER_SECRET_BOOK}
export TWITTER_ACCESS_TOKEN=${TWITTER_ACCESS_TOKEN_BOOK}
export TWITTER_ACCESS_TOKEN_SECRET=${TWITTER_ACCESS_TOKEN_SECRET_BOOK}

export COG_ARGC="2" # <1>
export COG_ARGV_0="Hello"
export COG_ARGV_1="World"

./tweet_cog_wrapper.sh # <2>
