== Introducing Cog

**Cog** brings the power of the command line to the place you collaborate with your team all the time -- your chat window.

Powerful access control means you can collaborate around even the most sensitive tasks with confidence. A focus on extensibility and adaptability means that you can respond quickly to the unexpected, without your team losing visibility.

=== Current Features

Cog is under heavy development and getting smarter all the time. This list of features gives you an idea of how Cog was built as well as the things that Cog knows how to do.

==== Extensibility image:images/extensible.svg["Extensible",width=200,height=200,float="left"]

Build new bot commands in any language

Commands return structured data to allow for creative adaptation in pipelines

Built in templating allows the command response to be formatted for the current chat provider without embedding markup in your logic

''''

==== Adaptability image:images/adaptability.svg["Adaptable",width=200,height=200,float="left"]

Unix-style pipelines allow you to combine a series of simple commands to solve complex, unexpected problems

Support for output redirection lets you make sure everyone is in the loop

''''

==== Security image:images/security.svg["Secure",width=200,height=200,float="left"]

Fine-grained command permissions give you confidence in using chatops for even the most sensitive workflows

Users, Groups, and Roles allow you to organize access control for ease of management

Audit logging for commands and administrative functions keep track of everything that happens with Cog

''''

==== Chat-Provider Agnostic image:images/chat-provider_agnostic.svg["Chat-Agnostic",width=200,height=200,float="left"]

Current support for Slack and Hipchat

...other chat clients are on the roadmap!

''''

Keep up to date on all things Cog by following icon:twitter[] https://twitter.com/operableinc[@OperableInc] on Twitter. Also, contact us at anytime via info@operable.io.

**Current version:** (https://github.com/operable/cog/releases[Changelog])

**Roadmap:** https://github.com/operable/cog/milestone/18[2H 2016 Roadmap]

== Get Started
Here are a few things you will need to do first.

. Join our http://slack.operable.io/[Slack Cog Public Chat] to chat with the Operable team and the Cog community. This is the best place to get realtime help.
. Head over to the <<Installation_Guide,Installation Guide>> and start installing Cog. Have questions? Ask us!
. Once installed, make Cog do something. Read up on <<Commands_and_Bundles,Commands and Bundles>>
. Do you want to expand Cog's command capabilities? Easy, start <<Building_Command_Bundles,Building Command Bundles>>.
. Looking for Enterprise solutions like a fully integrated Cog, dedicated support, or consultation by our team? Read more on our http://operable.io/enterprise.html[Enterprise page]. 

=== Communication
Let's set expectations. If you have a question, concern, idea, helpful hint, or want to tell us that you are hungry, we are listening. Please be as candid with us as possible. You can't hurt our feelings...too much. So that we can communicate as easily as possible we have several channels that you can use at anytime.

**GitHub Issues**
If you find an issue, please write it up as a https://github.com/operable/cog/issues[GitHub Issue]

**Cog Public Chat via Slack**
Chat with Operable engineers and the growing community in the http://slack.operable.io[Cog public Slack] channel.

=== User experience feedback
We want to know everything about how your experience with Cog is going. You cannot hurt our feelings! Tell us how we can make Cog a better ChatOps tool for you. Want to share your experience directly with someone at Operable? Find Shelton in our http://slack.operable.io[Cog public Slack] and message him directly.
