#!/bin/sh

export TWITTER_CONSUMER_KEY=${TWITTER_CONSUMER_KEY_BOOK}
export TWITTER_CONSUMER_SECRET=${TWITTER_CONSUMER_SECRET_BOOK}
export TWITTER_ACCESS_TOKEN=${TWITTER_ACCESS_TOKEN_BOOK}
export TWITTER_ACCESS_TOKEN_SECRET=${TWITTER_ACCESS_TOKEN_SECRET_BOOK}

./tweet.rb This is an interesting tweet
